### ISSUE TITLE
Conversations page bug

### ISSUE THREAD

**Issue by jsedoc** [chateval/application#29]
When selecting the conversation dataset and no model the backend throws an error

`Conversations._callee$
./pages/conversations.js:30
  27 | const prompts = promptsData.prompts.slice(0, 200);
  28 | 
  29 | let responses = [];
> 30 | for (const model of this.state.models) {
  31 |   const responsesRequest = await fetch('https://api.chateval.org/api/responses?evalset=' + this.state.evalset + "&model_id=" + model.value);
  32 |   const responsesData = await responsesRequest.json();
  33 |   responses.push({ model_id: model.value, responses: responsesData.responses.slice(0, 200), name: model.label });
View compiled
▼ 5 stack frames were expanded.
tryCatch
./node_modules/regenerator-runtime/runtime.js:62
Generator.invoke [as _invoke]
./node_modules/regenerator-runtime/runtime.js:288
Generator.prototype.(anonymous function) [as next]
./node_modules/regenerator-runtime/runtime.js:114
asyncGeneratorStep
https://chateval.org/_next/static/development/pages/conversations.js:13036:103
_next
https://chateval.org/_next/static/development/pages/conversations.js:13038:194`

**Comment by kirubarajan** [comment]
Resolved.
